### ISSUE TITLE
Ability to specify owner or protection type.

### ISSUE THREAD

**Issue by MC-MrBirdy** [pop4959/BoltWorldGuard#1]
Having the ability to specify the owner or protection type to execute the action on.
`/protectregion <region> -t:<type> -o:<owner>`
`/purgeregion <region> -t:<type> -o:<owner>`

Examples:
- `/protectregion spawn -o:Steve`
  Protect every protect-able at the region 'spawn' with the owner 'Steve'
- `/protectregion spawn -t:oak_trapdoor -o:Steve`
  Protect all 'oak trapdoors' at the region 'spawn' with the owner 'Steve'

**Comment by pop4959** [comment]
This is implemented; see the [changelog](https://modrinth.com/plugin/boltworldguard/version/1.0.1) on Modrinth for usage!
